version: "3.7"

services:
  cakewallet:
    build:
      context: ./app
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - cakewallet-data:/data
    environment:
      - DISPLAY=:0

volumes:
  cakewallet-data:
